Adjusted schema versions; adjusted test data to match.
eclipse-ee4j/jakartaee-schemas pull request #33
Opened 2022-01-12 16:56 UTC by tbitonti

Adjusted schema versions to match the specification versions for schemas which were updated.  Adjusted test data to match.

2022-01-12 17:00 UTC, tbitonti commented
For issue #32 "Missing schema version updates"

2022-01-19 08:22 UTC, ivargrimstad commented
This is a bit big to review. Please split it into one PR per schema update. Also note that some of the schemas will not change in 10. E.g. there is no EJB 5.0, so that schema must stay as is.

2022-01-19 08:23 UTC, ivargrimstad requested changes
Please split into one PR per schema

2022-01-19 08:23 UTC, ivargrimstad commented on xml/src/ejb-jar_5_0.xsds
> +	    version="5.0">
Nope, EJB is not updated for EE 10

2022-01-28 12:01 UTC, closed without merging